var express = require('express');
var router = express.Router();
var trainings = require('./trainings');
router.use('/api/trainings', trainings);
var customer = require('./customer');
router.use('/api/customer', customer);
var person = require('./person');
router.use('/api/person', person);
var contactus = require('./contactus');
router.use('/api/contactus', contactus);
var listOfCustomers = require('./listOfCustomers');
router.use('/api/listOfCustomers', listOfCustomers);
module.exports = router;